apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
spec:
  containers:
    - name: nginx-container
      image: nginx:alpine
      imagePullPolicy: Always
      resources:
        limits:
          cpu: 500m
          memory: 256Mi
        requests:
          cpu: 256m
          memory: 256Mi