apiVersion: v1
kind: Pod
metadata:
  name: sandeep-pod
  labels:
    app: nginx
    env: prod
spec:
  containers:
    - name: nginx-container
      image: nginx
      resources:
        requests:
          cpu: 250m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi
