apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding-developer
subjects:
  - kind: user 
    name: devuser
    apiGroup: rbac.authorization.k8s.io
roleRef:
    kind: Role 
    name: developer
    apiGroup: rbac.authorization.k8s.io
