apiVersion: v1
kind: Pod
metadata:
  name: jenkins-pod
spec:
  containers:
    - name: jenkins-containers
      image: jenkins/jenkins:lts-jdk11
      volumeMounts:
      - name: jenkins-data
        mountPath: /var/jenkins_home
  volumes:
    - name: jenkins-data
      hostPath:
        path: /home/abhishek/jenkins/
        type: DirectoryOrCreate