apiVersion: batch/v1
kind: Job
metadata:
  name: hello1
spec:
  template:
    # This is the pod template
    spec:
      containers:
      - name: hello
        image: busybox
        command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 60']
      restartPolicy: OnFailure