apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-pod
  labels:
    app: ubuntu
spec:
  containers:
    - name: ubuntu-container
      image: ubuntu
      command: ["sleep"]
      args: ["200"]
      env:
      -  name: "fname"
         value: "Abhishek"
      -  name: "lname"
         value: "Chordia"
      resources:
        limits:
          cpu: 500m
          memory: 256Mi
        requests:
          cpu: 256m
          memory: 256Mi