apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-pod
  labels:
    app: ubuntu
    env: test
spec:
  containers:
    - name: ubuntu-container
      image: ubuntu
      command:
        - "sleep"
        - "100"
      env:
        - name: "fname"
          value: "Abhishek"
        - name: "lname"
          value: "Chordia"
  restartPolicy: OnFailure