apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
spec:
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-container
          image: nginx:alpine
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 250m
              memory: 256Mi
  replicas: 2
  selector:
    app: nginx