apiVersion: v1
kind: Pod
metadata:
  name: multicontainer-pods
  labels:
    app: multicontainer
spec:
  containers:
    - name: nginx-container
      image: nginx
      resources:
        limits:
          cpu: 500m
          memory: 256Mi
        requests:
          cpu: 256m
          memory: 256Mi
    - name: busybox-container
      image: busybox
      resources:
        limits:
          cpu: 500m
          memory: 256Mi
        requests:
          cpu: 256m
          memory: 256Mi