apiVersion: v1
kind: Pod
metadata:
  name: nginx-nodeaffinity-pod
spec:
  containers:
    - name: nginx
      image: nginx:alpine 
      resources:
        limits:
          cpu: 250m
          memory: 256Mi
        requests:
          cpu: 250m
          memory: 256Mi
  affinity:
    nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: size
                operator: In
                values:
                  - Large