apiVersion: v1
kind: Pod
metadata:
  name: nginx-nodename-pod
spec:
  containers:
      - name: nginx
        image: nginx:alpine
        resources:
          limits:
            cpu: 250m
            memory: 256Mi
          requests:
            cpu: 250m
            memory: 256Mi
  nodeName: gke-testcluster-default-pool-128973e1-ljds