apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
  labels:
    app: nginx
    env: test
spec:
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx
        env: test
    spec:
      containers:
        - name: nginx-container
          image: nginx
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
  replicas: 2
  selector:
    matchLabels:
      app: nginx
      env: test